seed: 1

type: render

data:
  image_size: [256, 256]

renderer:
  type: sphere_tracing
  chunk_size: 8192
  near: 0.0
  far: 5.0
  max_iters: 64

sampler:
  type: stratified
  n_pts_per_ray:
  min_depth:
  max_depth:

implicit_function:
  type: sdf_surface
  sdf:
    type: complex_scene
    sphere1:
      center:
        val: [0.0, -1.0, -2.0]
        opt: False
      radius:
        val: 0.5
        opt: False
    sphere2:
      center:
        val: [1.0, 1.0, -3.0]
        opt: False
      radius:
        val: 0.75
        opt: False
    torus1:
      center:
        val: [-1.0, -1.0, -2.5]
        opt: False
      radii:
        val: [1.0, 0.25]
        opt: False
    box1:
      center:
        val: [2.0, -2.0, -4.0]
        opt: False
      side_lengths:
        val: [1.5, 1.5, 1.5]
        opt: False

  feature:
    rainbow: True
    val: [1.0, 1.0, 1.0]
    opt: False
